# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # NodeJS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache
      uses: actions/cache@v1.1.2
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

    # Project deps
    - name: Install Dependencies
      run: npm install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    # App project tests
    - name: Test
      run: npm run test

    # Build dist bundle
    - name: Build
      run: npm run build

    # Publish
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}


